### ISSUE TITLE
Code review - feedback

### ISSUE THREAD

**Issue by MHUS25** [Rupieeroo/Fizz-Buzz-in-Python#1]
Hey Rupert,

Here's my feedback:

- Commits show a good TDD process following the red-green-refactor loop.

- The ‘TDD steps’ section in your README explains your approach well and shows you can justify the way you work.

- Code is well written and readable, I agree this project is good evidence for programming fluently.

**Comment by rupert-adams** [comment]
Thank you so much for the feedback!
